.PHONY: run format build

run:
	VITE_DB_URL=http://localhost:5173/data/db.sqlite3 \
	VITE_BLOBS_URL=http://localhost:5173/data/blobs \
		yarn run dev

format:
	yarn run format

build:
	yarn run build
